### ISSUE TITLE
runretinotopy timing question

### ISSUE THREAD

**Issue by tommybotch** [cvnlab/knkutils#8]
Hello -- thank you for sharing this code for running retinotopy! 

I am using the default parameters of the runretinotopy.m script and have downloaded the required files. I am able to successfully run the scripts, and the scripts run to completion. Despite using the default configurations (e.g., 60 Hz display, 4 FPS, expected duration of 500s), the stimulus finishes earlier than expected:

![retinotopy_output](https://github.com/user-attachments/assets/7dfe94d9-10d5-4410-938c-1b2a6bda372b)

![retinotopy_graph](https://github.com/user-attachments/assets/8e7042f2-3320-465f-9360-512eeaaa12b0)

I have tried this using both 2018b and 2023b versions of MATLAB. Is this expected behavior? Or am I missing some configuration to have the scripts run for the full 500s? Sorry to bother, and thanks in advance for the help.

**Comment by kendrickkay** [comment]
Hello,

Based on the information you provided, things look "correct" in the sense that it seems to be performing reliably.

The timeframes inspection indicates no dropped frames, and your test ran with:
   52.7 ms between frames
   18.97 Hz

Now, my recollection is that the experiment was intended to last ~300 s (for each run) with a 15 Hz rate for the frames of the stimulus.  Is that what you intend?

Can you confirm that the refresh rate of your monitor is 60 Hz?

It appears based on the numbers that the refresh rate of your monitor may be 75 Hz.

Try forcing it to run in 60 Hz mode.  Otherwise, you could run at the current rate.  Or change the frameduration (i.e. how many monitor refreshes for each stimulus frame) to be a little higher.

Kendrick

**Comment by tommybotch** [comment]
Hi Kendrick --

Thanks for the help. I confirmed that the refresh rate of the monitor is 60 Hz, and went with the solution of increasing the frame duration (forcing the stimulus to last 300s). 

Closing the issue, thanks again!

Tommy
